# Generated by Django 5.2.17 on 2026-09-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="score_target",
            field=models.CharField(
                choices=[
                    ("ca1", "First CA"),
                    ("ca2", "Second CA"),
                    ("ca3", "Third CA"),
                    ("exam", "Examination"),
                ],
                max_length=10,
            ),
        ),
    ]
