# Generated by Django 5.2.17 on 2026-09-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_exam_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="push_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="submission",
            name="push_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
