# Generated by Django 5.2.17 on 2026-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_submission_push_error_submission_push_failed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, max_length=500, upload_to="questions/"),
        ),
    ]
