# Generated by Django 5.2.17 on 2026-09-30 12:06

import exams.models
from django.db import migrations, models


def give_each_exam_its_own_code(apps, schema_editor):
    # AddField evaluates the callable default once, so every existing exam
    # would otherwise share one code.
    Exam = apps.get_model("exams", "Exam")
    for exam in Exam.objects.all():
        exam.access_code = exams.models.new_access_code()
        exam.save(update_fields=["access_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="access_code",
            field=models.CharField(default=exams.models.new_access_code, max_length=6),
        ),
        migrations.RunPython(give_each_exam_its_own_code, migrations.RunPython.noop),
    ]
