# Generated by Django 5.2.17 on 2026-09-30 13:58

from django.db import migrations, models


def clear_auto_generated_codes(apps, schema_editor):
    # 0006 gave every exam a code automatically; codes are now issued by
    # management, so start everyone from "no code yet".
    apps.get_model("exams", "Exam").objects.update(access_code="")


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_exam_access_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="access_code",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.RunPython(clear_auto_generated_codes, migrations.RunPython.noop),
    ]
