# Generated by Django 5.2.17 on 2026-10-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_access_code_set_by_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="draft_answers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="submission",
            name="draft_seq",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
