# Generated by Django 5.2.17 on 2026-10-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_submission_autosave"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="text_answer",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="question",
            name="accepted_answers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[("mcq", "Multiple choice"), ("blank", "Fill in the blank")],
                default="mcq",
                max_length=10,
            ),
        ),
    ]
