# Generated by Django 5.2.17 on 2026-10-02 11:36

import django.db.models.deletion
from django.db import migrations, models


def copy_class_into_classes(apps, schema_editor):
    Exam = apps.get_model("exams", "Exam")
    for exam in Exam.objects.filter(klass__isnull=False, classes__isnull=True):
        exam.classes.add(exam.klass_id)


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0009_fill_in_the_blank"),
        ("roster", "0004_subject_grades"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="classes",
            field=models.ManyToManyField(related_name="exams", to="roster.syncedclass"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="klass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="roster.syncedclass",
            ),
        ),
        migrations.RunPython(copy_class_into_classes, migrations.RunPython.noop),
    ]
