# Generated by Django 5.2.17 on 2026-09-29 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncedManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raddai_id", models.PositiveIntegerField(unique=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("full_name", models.CharField(max_length=150)),
                ("role", models.CharField(blank=True, default="", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("must_change_password", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syncedmanager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
