# Generated by Django 5.2.17 on 2026-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0003_syncedstudent_current_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncedsubject",
            name="grades",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
